### PR TITLE
Fixed paths for Base presets

### PR DESCRIPTION
**Pull request by kwyxz**
The current Base presets don't work properly at least on Linux, due to a path problem.
This commit fixes the issue.

### CODE REVIEW

**Comment by HyperspaceMadness** [comment]
Hi, are you using one of the Retroarch Nightlies to test this? Or the released version of Retroarch?

**Comment by kwyxz** [comment]
I built RetroArch from git an hour ago, using commit d3dc3ee989ec6a4903c689907ffc47027f71f776

**Comment by kwyxz** [comment]
The issue with this:
```:/shaders/shaders_slang/stock.slang```
seems to be that the `:` character is interpreted as "the folder retroarch is being run from" which, on Linux, will often be `/usr/local/bin` or similar. Hence some shader files fail to load.

**Comment by HyperspaceMadness** [comment]
So that's right, it is looking from the root of the retroarch folder which is where the shaders folder is, isn't it?

**Comment by kwyxz** [comment]
> it is looking from the root of the retroarch folder which is where the shaders folder is, isn't it?

Not on Linux and other POSIX systems, no. When building from source, only the following is installed:

```
❯ sudo make install
mkdir -p /usr/local/bin 2>/dev/null || /bin/true
mkdir -p /etc 2>/dev/null || /bin/true
mkdir -p /usr/local/share/applications 2>/dev/null || /bin/true
mkdir -p /usr/local/share/metainfo 2>/dev/null || /bin/true
mkdir -p /usr/local/share/doc/retroarch 2>/dev/null || /bin/true
mkdir -p /usr/local/share/man/man6 2>/dev/null || /bin/true
mkdir -p /usr/local/share/pixmaps 2>/dev/null || /bin/true
cp retroarch /usr/local/bin
cp tools/cg2glsl.py /usr/local/bin/retroarch-cg2glsl
cp retroarch.cfg /etc
cp com.libretro.RetroArch.appdata.xml /usr/local/share/metainfo
cp retroarch.desktop /usr/local/share/applications
cp docs/retroarch.6 /usr/local/share/man/man6
cp docs/retroarch-cg2glsl.6 /usr/local/share/man/man6
cp media/retroarch.svg /usr/local/share/pixmaps
cp COPYING /usr/local/share/doc/retroarch
cp README.md /usr/local/share/doc/retroarch
chmod 755 /usr/local/bin/retroarch
chmod 755 /usr/local/bin/retroarch-cg2glsl
chmod 644 /etc/retroarch.cfg
chmod 644 /usr/local/share/applications/retroarch.desktop
chmod 644 /usr/local/share/metainfo/com.libretro.RetroArch.appdata.xml
chmod 644 /usr/local/share/man/man6/retroarch.6
chmod 644 /usr/local/share/man/man6/retroarch-cg2glsl.6
chmod 644 /usr/local/share/pixmaps/retroarch.svg
Installing media assets...
Asset copying done.
```
The binary for `retroarch` is installed to `/usr/local/bin` while the shaders folder can be installed anywhere. 
Moreover, the shaders path is configurable through the settings and IMHO should not depend on the location of the Retroarch binary.

**Comment by kwyxz** [comment]
Another example : [Makefile](https://github.com/HyperspaceMadness/shaders_slang/blob/master/Makefile) in this very repository installs the shaders to `/usr/share/libretro/shaders/shaders_slang` - another location where the current paths would break.

**Comment by HyperspaceMadness** [comment]
Ok I see your point. I'll check things out on my end. Have you loaded any shaders in recent times and saved simple presets for per game or per core etc? These use the ":/" formatting as well for the path to their referenced presets

**Comment by kwyxz** [comment]
Have not, but I can take a look at this, thanks for letting me know!

Also I am assuming there's a similar issue with the `CRT_Alternate presets` but I haven't looked at them yet (I'm very happy with the Base ones)

Also, thank you for your awesome work, I love the Megabezels!

**Comment by HyperspaceMadness** [comment]
Thanks for going to the effort of making a PR. Since I am working on refactoring the presets right now, I'll just add these changes in with my next commits to the repos, so I'll close this PR.

**Comment by HyperspaceMadness** [comment]
> Have not, but I can take a look at this, thanks for letting me know!
> 
> Also I am assuming there's a similar issue with the `CRT_Alternate presets` but I haven't looked at them yet (I'm very happy with the Base ones)
> 
> Also, thank you for your awesome work, I love the Megabezels!

Hey there, I updated the presets so they are now using the ../.. instead of :/   so they should all hopefully work for you out of the box. The other presets have been updated as well and are now working.

Cheers!

**Pull request closed without merging**
